// src/routes/playbook/badges/+page.svelte
<script lang="ts">
  import Chip from '$lib/components/Chip.svelte';
  import StatusDot from '$lib/components/StatusDot.svelte';
</script>

<svelte:head><title>Badges — Playbook</title></svelte:head>

<h1 class="h2 mb-6">Badges</h1>

<section class="pb-section">
  <h2 class="pb-label">Chip Tones</h2>
  <div class="row">
    <Chip tone="primary">Primary</Chip>
    <Chip tone="secondary">Secondary</Chip>
    <Chip tone="tertiary">Tertiary</Chip>
    <Chip tone="warning">Warning</Chip>
    <Chip tone="success">Success</Chip>
    <Chip tone="error">Error</Chip>
    <Chip tone="surface">Surface</Chip>
  </div>
  <pre class="pb-code"><code>&lt;Chip tone="primary"&gt;Label&lt;/Chip&gt;
&lt;Chip tone="success"&gt;Active&lt;/Chip&gt;
&lt;Chip tone="error"&gt;Rejected&lt;/Chip&gt;</code></pre>
</section>

<section class="pb-section">
  <h2 class="pb-label">Chips with Icons (Common Patterns)</h2>
  <div class="row">
    <Chip tone="secondary">📝 Request</Chip>
    <Chip tone="warning">💡 Offer</Chip>
    <Chip tone="surface">🏷️ Mentoring</Chip>
    <Chip tone="surface">🏷️ Design</Chip>
    <Chip tone="tertiary">🏢 hAppenings CIC</Chip>
  </div>
</section>

<section class="pb-section">
  <h2 class="pb-label">Status Dot — Connection States</h2>
  <p class="text-sm opacity-60 mb-3">Designed for the violet navbar context. Shown on a matching background.</p>
  <div class="violet-band">
    <StatusDot status="connected" />
    <StatusDot status="checking" />
    <StatusDot status="disconnected" />
    <StatusDot status="error" />
  </div>
  <pre class="pb-code"><code>&lt;StatusDot status="connected" /&gt;
&lt;StatusDot status="checking" /&gt;
&lt;StatusDot status="disconnected" /&gt;
&lt;StatusDot status="error" /&gt;</code></pre>
</section>

<section class="pb-section">
  <h2 class="pb-label">Token Reference</h2>
  <table class="token-table">
    <thead><tr><th>Chip tone</th><th>Skeleton class</th></tr></thead>
    <tbody>
      <tr><td>primary</td><td><code>variant-soft-primary</code></td></tr>
      <tr><td>secondary</td><td><code>variant-soft-secondary</code></td></tr>
      <tr><td>success</td><td><code>variant-soft-success</code></td></tr>
      <tr><td>surface</td><td><code>variant-soft-surface</code></td></tr>
    </tbody>
  </table>
</section>

<style>
  .pb-section { background: #fff; border-radius: 12px; padding: 24px; margin-bottom: 20px; box-shadow: var(--shadow-sm); }
  .pb-label { font: 600 11px/16px var(--font-base); text-transform: uppercase; letter-spacing: .08em; color: var(--fg-3); margin: 0 0 16px; }
  .row { display: flex; flex-wrap: wrap; align-items: center; gap: 10px; }
  .violet-band {
    background: rgb(var(--color-primary-500)); border-radius: 10px; padding: 16px 20px;
    display: flex; flex-wrap: wrap; gap: 12px; align-items: center;
  }
  .pb-code { margin-top: 16px; background: rgb(var(--color-surface-900)); color: rgb(var(--color-surface-100)); border-radius: 8px; padding: 14px; font: 400 13px/20px var(--font-mono); overflow-x: auto; }
  .token-table { width: 100%; border-collapse: collapse; font: 400 13px/20px var(--font-base); margin-top: 8px; }
  .token-table th { text-align: left; font-weight: 600; padding: 6px 12px; border-bottom: 1px solid var(--border-1); }
  .token-table td { padding: 6px 12px; border-bottom: 1px solid var(--border-1); }
  .token-table code { font-family: var(--font-mono); font-size: 12px; }
</style>

// ui_kits/requests-and-offers/Badges.jsx
/* eslint-disable */

function Chip({ tone = 'primary', children }) {
  return <span className={`chip chip-${tone}`}>{children}</span>;
}

function StatusDot({ status = 'connected' }) {
  const map = {
    connected: { ic: '🟢', label: 'Connected' },
    checking: { ic: '🟡', label: 'Checking…' },
    disconnected: { ic: '🟠', label: 'Disconnected' },
    error: { ic: '🔴', label: 'Error' },
  };
  const s = map[status] || map.connected;
  return (
    <span className="status-pill">
      <span aria-hidden>{s.ic}</span>
      <span className="status-pill__label">{s.label}</span>
    </span>
  );
}

const badgeStyles = `
.chip {
  display: inline-flex; align-items: center; gap: 6px;
  border-radius: 9999px; padding: 4px 10px;
  font: 600 12px/18px var(--font-base);
  white-space: nowrap;
}
.chip-primary   { background: rgb(var(--color-primary-100));   color: rgb(var(--color-primary-800)); }
.chip-secondary { background: rgb(var(--color-secondary-100)); color: rgb(var(--color-secondary-900)); }
.chip-tertiary  { background: rgb(var(--color-tertiary-100));  color: rgb(var(--color-tertiary-800)); }
.chip-warning   { background: rgb(var(--color-warning-100));   color: rgb(var(--color-warning-800)); }
.chip-success   { background: rgb(var(--color-success-100));   color: rgb(var(--color-success-900)); }
.chip-error     { background: rgb(var(--color-error-100));     color: rgb(var(--color-error-800)); }
.chip-surface   { background: rgb(var(--color-surface-100));   color: rgb(var(--color-surface-800)); }

.status-pill {
  display: inline-flex; align-items: center; gap: 6px;
  border: 1px solid rgba(255,255,255,.25);
  background: rgba(255,255,255,.12);
  backdrop-filter: blur(4px);
  border-radius: 9999px; padding: 4px 12px;
  color: #fff; font: 500 12px/18px var(--font-base);
}
.status-pill__label { opacity: .9;}
`;

Object.assign(window, { Chip, StatusDot, badgeStyles });
