// src/routes/playbook/cards/+page.svelte
<script lang="ts">
  import ActionCard from '$lib/components/ActionCard.svelte';
  import ListingCard from '$lib/components/ListingCard.svelte';
  import Button from '$lib/components/Button.svelte';
</script>

<svelte:head><title>Cards — Playbook</title></svelte:head>

<h1 class="h2 mb-6">Cards</h1>

<section class="pb-section">
  <h2 class="pb-label">ActionCard — 3-up Grid</h2>
  <div class="action-grid">
    <ActionCard
      icon="🔍"
      title="Discover Opportunities"
      description="Browse active requests from community members looking for skills and support."
      ctaLabel="Browse Requests"
      ctaTone="secondary"
    />
    <ActionCard
      icon="🌟"
      title="Offer Your Skills"
      description="Share what you can contribute. Post skills, time, or resources for the community."
      ctaLabel="Post an Offer"
      ctaTone="warning"
    />
    <ActionCard
      icon="🏘️"
      title="Explore Community"
      description="Meet members and organizations working toward a collaborative local economy."
      ctaLabel="Meet People"
      ctaTone="tertiary"
    />
  </div>
  <pre class="pb-code"><code>&lt;ActionCard
  icon="🔍"
  title="Discover Opportunities"
  description="Browse active requests…"
  ctaLabel="Browse Requests"
  ctaTone="secondary"
/&gt;</code></pre>
</section>

<section class="pb-section">
  <h2 class="pb-label">ListingCard — Request</h2>
  <div style="max-width: 420px;">
    <ListingCard
      kind="request"
      title="Looking for a Holochain mentor"
      owner="Anya Kovaleva"
      ownerInitial="A"
      time="2 hours ago"
      description="I'm building my first hApp and need guidance on zome architecture and entry validation. Happy to exchange language tutoring."
      tags="Holochain,Mentoring,Rust"
    />
  </div>
</section>

<section class="pb-section">
  <h2 class="pb-label">ListingCard — Offer</h2>
  <div style="max-width: 420px;">
    <ListingCard
      kind="offer"
      title="UI/UX design consultation — 2 sessions"
      owner="Marco Delgado"
      ownerInitial="M"
      time="Yesterday"
      description="I can help with wireframes, user flows, and visual design reviews. I specialize in accessibility-first design for web applications."
      tags="Design,UX,Figma,Accessibility"
    />
  </div>
  <pre class="pb-code"><code>&lt;ListingCard
  kind="offer"
  title="UI/UX design consultation"
  owner="Marco Delgado"
  ownerInitial="M"
  time="Yesterday"
  description="…"
  tags="Design,UX,Figma"
/&gt;</code></pre>
</section>

<section class="pb-section">
  <h2 class="pb-label">Banner — Gradient Layout Pattern</h2>
  <div class="banner">
    <h2>Welcome to Requests &amp; Offers</h2>
    <p>A peer-to-peer exchange platform for the hAppenings community. Share skills, resources, and time.</p>
    <div style="display: flex; gap: 10px; flex-wrap: wrap;">
      <Button variant="secondary">Browse Requests</Button>
      <Button variant="on-violet">Post an Offer</Button>
    </div>
  </div>
  <pre class="pb-code"><code>&lt;div class="banner"&gt;
  &lt;h2&gt;Heading&lt;/h2&gt;
  &lt;p&gt;Description…&lt;/p&gt;
&lt;/div&gt;</code></pre>
</section>

<style>
  .pb-section { background: #fff; border-radius: 12px; padding: 24px; margin-bottom: 20px; box-shadow: var(--shadow-sm); }
  .pb-label { font: 600 11px/16px var(--font-base); text-transform: uppercase; letter-spacing: .08em; color: var(--fg-3); margin: 0 0 16px; }
  .action-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 16px; }
  .pb-code { margin-top: 16px; background: rgb(var(--color-surface-900)); color: rgb(var(--color-surface-100)); border-radius: 8px; padding: 14px; font: 400 13px/20px var(--font-mono); overflow-x: auto; }
  .banner {
    border-radius: 16px; padding: 32px; color: #fff; box-shadow: var(--shadow-lg);
    background: linear-gradient(90deg, rgb(var(--color-primary-500)) 0%, rgb(var(--color-secondary-500)) 100%);
  }
  .banner h2 { margin: 0 0 8px; font: 700 28px/34px var(--font-base); }
  .banner p  { margin: 0 0 16px; font: 400 16px/24px var(--font-base); opacity: .92; }
</style>

// ui_kits/requests-and-offers/Cards.jsx
/* eslint-disable */

function ActionCard({ icon, title, description, ctaLabel, ctaTone = 'secondary', onClick }) {
  return (
    <div className="action-card" onClick={onClick} role="button" tabIndex={0}>
      <div className="action-card__icon">{icon}</div>
      <h3 className="action-card__title">{title}</h3>
      <p className="action-card__desc">{description}</p>
      {ctaLabel ? (
        <span className={`action-card__cta cta-${ctaTone}`}>{ctaLabel}</span>
      ) : null}
    </div>
  );
}

function ListingCard({ kind = 'request', title, owner, ownerInitial, time, tags = [], description, onClick }) {
  const tone = kind === 'request' ? 'secondary' : 'warning';
  const icon = kind === 'request' ? '📝' : '💡';
  return (
    <div className="listing-card" onClick={onClick} role="button" tabIndex={0}>
      <div className="listing-card__head">
        <span className={`chip chip-${tone}`}>{icon} {kind === 'request' ? 'Request' : 'Offer'}</span>
        <span className="listing-card__time">{time}</span>
      </div>
      <h3 className="listing-card__title">{title}</h3>
      <p className="listing-card__desc">{description}</p>
      <div className="listing-card__foot">
        <span className="avatar"><span>{ownerInitial}</span></span>
        <span className="listing-card__owner">{owner}</span>
        <span className="listing-card__tags">
          {tags.map(t => <span key={t} className="chip chip-surface">{t}</span>)}
        </span>
      </div>
    </div>
  );
}

const cardStyles = `
.action-card {
  background: #fff; border: 1px solid rgb(var(--border-1));
  border-radius: 12px; padding: 24px; box-shadow: var(--shadow-md);
  text-align: center; cursor: pointer;
  transition: box-shadow 150ms, border-color 150ms, transform 150ms;
}
.action-card:hover { box-shadow: var(--shadow-lg); border-color: rgb(var(--color-primary-300)); }
.action-card:hover .action-card__icon { transform: scale(1.1); }
.action-card__icon { font-size: 40px; margin-bottom: 10px; transition: transform 150ms; }
.action-card__title { margin: 0 0 8px; font: 600 18px/24px var(--font-base); color: rgb(var(--fg-1)); }
.action-card__desc { margin: 0 0 14px; font: 400 14px/22px var(--font-base); color: rgb(var(--fg-2)); }
.action-card__cta { display: inline-block; border-radius: 9999px; padding: 8px 18px; font: 600 13px/20px var(--font-base); }
.cta-secondary { background: rgb(var(--color-secondary-500)); color: #111;}
.cta-warning   { background: rgb(var(--color-warning-500)); color: #111;}
.cta-tertiary  { background: rgb(var(--color-tertiary-500)); color: #111;}
.cta-primary   { background: rgb(var(--color-primary-500)); color: #fff;}

.listing-card {
  background: #fff; border: 1px solid rgb(var(--border-1));
  border-radius: 12px; padding: 18px; box-shadow: var(--shadow-sm);
  cursor: pointer;
  transition: box-shadow 150ms, border-color 150ms, transform 100ms;
  display: flex; flex-direction: column; gap: 10px;
}
.listing-card:hover { box-shadow: var(--shadow-md); border-color: rgb(var(--color-primary-300)); }
.listing-card__head { display: flex; align-items: center; justify-content: space-between; }
.listing-card__time { font: 400 12px/16px var(--font-base); color: rgb(var(--fg-3)); }
.listing-card__title { margin: 0; font: 600 18px/24px var(--font-base); color: rgb(var(--fg-1)); }
.listing-card__desc  { margin: 0; font: 400 14px/22px var(--font-base); color: rgb(var(--fg-2)); display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden;}
.listing-card__foot  { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }
.listing-card__owner { font: 500 13px/18px var(--font-base); color: rgb(var(--fg-2)); }
.listing-card__tags  { display: flex; gap: 6px; margin-left: auto; flex-wrap: wrap;}

.avatar {
  width: 28px; height: 28px; border-radius: 9999px;
  background: rgb(var(--color-primary-200));
  color: rgb(var(--color-primary-800));
  display: inline-grid; place-items: center;
  font: 700 12px/1 var(--font-base);
}

/* gradient banner used on home and CTAs */
.banner {
  border-radius: 16px; padding: 32px;
  color: #fff; box-shadow: var(--shadow-lg);
  background: linear-gradient(90deg, rgb(var(--color-primary-500)) 0%, rgb(var(--color-secondary-500)) 100%);
}
.banner h2 { margin: 0 0 8px; font: 700 28px/34px var(--font-base);}
.banner p  { margin: 0 0 16px; font: 400 16px/24px var(--font-base); opacity: .92;}

.cta-row {
  display: grid; grid-template-columns: 1fr 1fr; gap: 16px;
}
.cta-tile {
  border-radius: 12px; padding: 22px;
  color: #fff; box-shadow: var(--shadow-md);
  display: flex; align-items: center; gap: 16px;
  cursor: pointer;
  transition: box-shadow 150ms, transform 150ms;
}
.cta-tile:hover { box-shadow: var(--shadow-xl); }
.cta-tile:hover .cta-tile__icon { transform: scale(1.1); }
.cta-tile__icon { font-size: 40px; transition: transform 150ms; }
.cta-tile h3 { margin: 0 0 4px; font: 700 22px/28px var(--font-base);}
.cta-tile p  { margin: 0; opacity: .9; font: 400 14px/20px var(--font-base);}
.cta-tile--requests { background: linear-gradient(90deg, rgb(var(--color-secondary-500)), rgb(var(--color-secondary-600))); color: #1a1a1a;}
.cta-tile--offers   { background: linear-gradient(90deg, rgb(var(--color-warning-500)),   rgb(var(--color-warning-600)));}
`;

Object.assign(window, { ActionCard, ListingCard, cardStyles });
